name: Create Manifest

on:
  workflow_call:
    inputs:
      fetch_depth:
        required: false
        type: number
        default: 1
      build_default_branch_manifest:
        type: boolean
        default: false
      image_name:
        required: false
        type: string
    secrets:
      GH_TOKEN_USER:
        required: true
      GH_TOKEN:
        required: true

jobs:
  create-manifest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: ${{ inputs.fetch_depth }}
      - name: Checkout private action
        uses: actions/checkout@v4
        with:
          repository: babelcloud/docker-manifest-create-push-action
          ref: v2
          token: ${{ secrets.GH_TOKEN }}
          path: ./.github/actions/docker-manifest-create-push-action
      - name: Resolve image name
        run: echo "IMAGE_NAME=ghcr.io/${{ inputs.image_name || github.repository }}" >> $GITHUB_ENV
      - name: Resolve image tag with rev
        run: echo "IMAGE_REV_TAG=${IMAGE_NAME}:$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Resolve image tag with branch name
        if: ${{ inputs.build_default_branch_manifest && github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        run: echo "IMAGE_BRANCH_TAG=${IMAGE_NAME}:${GITHUB_REF_NAME}" >> $GITHUB_ENV
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_TOKEN_USER }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Create and push manifest
        uses: ./.github/actions/docker-manifest-create-push-action
        with:
          manifest-list: ${{ env.IMAGE_REV_TAG }}
          manifests: ${{ env.IMAGE_REV_TAG }}-amd64,${{ env.IMAGE_REV_TAG }}-arm64
      - name: Create and push manifest with branch name
        if: ${{ inputs.build_default_branch_manifest && github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        uses: ./.github/actions/docker-manifest-create-push-action
        with:
          manifest-list: ${{ env.IMAGE_BRANCH_TAG }}
          manifests: ${{ env.IMAGE_BRANCH_TAG }}-amd64,${{ env.IMAGE_BRANCH_TAG }}-arm64
      - name: Create and push manifest with tag
        if: ${{ github.ref_type == 'tag' }}
        uses: ./.github/actions/docker-manifest-create-push-action
        with:
          manifest-list: ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          manifests:  ${{ env.IMAGE_REV_TAG }}-amd64,${{ env.IMAGE_REV_TAG }}-arm64
