name: Builds

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/image-build.yml
    with:
      submodule_path: gbox-mcp-server
    secrets:
      GH_TOKEN_USER: ${{ secrets.GH_TOKEN_USER }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
